import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../components/NavBar'
import Question from '../components/question'
import QuestionEditor from '../components/questionEditor'
import QuestionEditorList from '../components/questionEditorList'
import styles from '../styles/Home.module.css'
import Link from 'next/link' 

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Educatr!

          {/* auth0 login:
          <a href="/api/auth/login">Login</a>

          <a href="/api/auth/logout">Logout</a> */}
        </h1>

        <p className={styles.description}>
          Educatr is a free knowledge-sharing website that allows everyone to learn and study from lessons added by educators, professors, and even general users!
        </p>

        <div className={styles.grid}>
          <a href="/edit/1" className={styles.card}>
            <h2>Create New Lesson &rarr;</h2>
            <p>Make your new lesson from scratch about one of the subjects and add a question too!</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>View New Lessons &rarr;</h2>
            <p>Explore latest interactive lessons in all subject areas!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Subjects &rarr;</h2>
            <p>Look through our academic subject categories including math, science, English.</p>
          </a>

          <a
            href="/lessons/1"
            className={styles.card}
          >
            <h2>Your Lessons &rarr;</h2>
            <p>
              View and edit the lessons you have created. 
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
